language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ailuffy"
  - git config user.email "ailuffy@outlook.com"
  - git add .
  - git commit -m " ':memo:' Update blog"
  - git push --force --quiet "https://${blog-token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-generator
env:
 global:
   - GH_REF: github.com/AIluffy/AIluffy.github.io.git